sudo: false
language: node_js
node_js:
  - 0.10
  - 0.12
  - stable

addons:
  firefox: "latest"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    - damon.oehlman@gmail.com